# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MessageApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MessageApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.3.0'

  # Facebook Login
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'


end
